"""users consent fields

Revision ID: 32f352f033c5
Revises: b700638ca4c5
Create Date: 2023-08-08 13:23:55.185890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f352f033c5'
down_revision = 'b700638ca4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('consent_to_send_emails', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('consent_to_cookies', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_consent_to_cookies'), 'user', ['consent_to_cookies'], unique=False)
    op.create_index(op.f('ix_user_consent_to_send_emails'), 'user', ['consent_to_send_emails'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_consent_to_send_emails'), table_name='user')
    op.drop_index(op.f('ix_user_consent_to_cookies'), table_name='user')
    op.drop_column('user', 'consent_to_cookies')
    op.drop_column('user', 'consent_to_send_emails')
    # ### end Alembic commands ###
