"""moved upvotes and downvotes to definition

Revision ID: 73edc2773cd0
Revises: 32f352f033c5
Create Date: 2023-08-09 17:09:26.409305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73edc2773cd0'
down_revision = '32f352f033c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definition', sa.Column('upvotes', sa.Integer(), nullable=True))
    op.add_column('definition', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.drop_column('word', 'downvotes')
    op.drop_column('word', 'upvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('upvotes', sa.INTEGER(), nullable=True))
    op.add_column('word', sa.Column('downvotes', sa.INTEGER(), nullable=True))
    op.drop_column('definition', 'downvotes')
    op.drop_column('definition', 'upvotes')
    # ### end Alembic commands ###
