"""empty message

Revision ID: 9b851b727101
Revises: d1f7068438e9
Create Date: 2024-01-30 16:27:20.019225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b851b727101'
down_revision = 'd1f7068438e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('definition', schema=None) as batch_op:
        batch_op.alter_column('upvotes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('downvotes',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('definition', schema=None) as batch_op:
        batch_op.alter_column('downvotes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('upvotes',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
